on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: studentattendanceaks.azurecr.io
        username: ${{ secrets.acr_studentattendanceaks_username }}
        password: ${{ secrets.acr_studentattendanceaks_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t studentattendanceaks.azurecr.io/onlinestudentattendanceaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push studentattendanceaks.azurecr.io/onlinestudentattendanceaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_onlinestudentattendanceaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep onlinestudentattendanceaks89d3 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace onlinestudentattendanceaks89d3`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: onlinestudentattendanceaks89d3
        container-registry-url: studentattendanceaks.azurecr.io
        container-registry-username: ${{ secrets.acr_studentattendanceaks_username }}
        container-registry-password: ${{ secrets.acr_studentattendanceaks_password }}
        secret-name: onlinestudendockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: onlinestudentattendanceaks89d3
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          studentattendanceaks.azurecr.io/onlinestudentattendanceaks:${{ github.sha }}
        imagepullsecrets: |
          onlinestudendockerauth
