apiVersion : apps/v1
kind: Deployment
metadata:
  name: "onlinestudentattendanceaks-c95c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "onlinestudentattendanceaks-c95c"
  template:
    metadata:
      labels:
        app: "onlinestudentattendanceaks-c95c"
    spec:
      containers:
        - name: "onlinestudentattendanceaks-c95c"
          image: "studentattendanceaks.azurecr.io/onlinestudentattendanceaks"
          ports:
          - containerPort: 80